eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://${tpd.appconfig.peer2-address}/eureka

spring:
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@clubmanagementsystem-liwrx.gcp.mongodb.net/${MONGO_DATABASE}?retryWrites=true
      authentication-database: admin
  application:
    name: core-player-service

tpd:
  appconfig:
    peer1-address: eureka-peer1:8761
    peer2-address: eureka-peer2:8762

server:
  port: 8080